package com.aichainid.ai;

import com.aichainid.ai.dto.AiPermissionRequest;
import com.aichainid.ai.dto.AiPermissionResponse;
import com.aichainid.ai.dto.AiRiskAlertResponse;
import com.aichainid.ai.dto.AiRiskRequest;
import com.aichainid.ai.dto.AiRiskResponse;
import com.aichainid.common.response.ApiResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * Proxy controller — the frontend calls these Java endpoints, which in turn
 * forward to the Python FastAPI AI microservice.
 *
 * Endpoints:
 *   POST /api/ai/recommend-permissions   → AI permission recommendation
 *   POST /api/ai/risk-score              → AI risk & anomaly detection
 *   GET  /api/ai/risk-alerts             → AI-generated security alerts
 *   GET  /api/ai/health                  → Check if Python AI service is up
 */
@RestController
@RequestMapping("/api/ai")
@Tag(name = "AI Services", description = "AI-powered permission recommendation and risk/anomaly detection")
public class AiController {

    private final AiServiceClient aiServiceClient;

    public AiController(AiServiceClient aiServiceClient) {
        this.aiServiceClient = aiServiceClient;
    }

    @PostMapping("/recommend-permissions")
    @Operation(
        summary = "Get AI permission recommendation",
        description = "Calls the Python AI microservice to recommend ALLOW/REVIEW/DENY for each requested resource "
                    + "based on role, department, credentials, and project context. "
                    + "Result is a recommendation only — final access must be admin-approved."
    )
    public ResponseEntity<ApiResponse<AiPermissionResponse>> recommendPermissions(
            @Valid @RequestBody AiPermissionRequest request) {

        AiPermissionResponse result = aiServiceClient.getPermissionRecommendation(request);
        return ResponseEntity.ok(ApiResponse.success("AI permission recommendation generated", result));
    }

    @PostMapping("/risk-score")
    @Operation(
        summary = "Get AI risk & anomaly score for an access event",
        description = "Calls the Python AI microservice (RandomForestRegressor + IsolationForest) to compute "
                    + "a 0-100 risk score and classify as LOW/MEDIUM/HIGH with a ALLOW/ADMIN_REVIEW/BLOCK decision. "
                    + "Implements step 8 of the architecture: continuous AI security monitoring."
    )
    public ResponseEntity<ApiResponse<AiRiskResponse>> getRiskScore(
            @Valid @RequestBody AiRiskRequest request) {

        AiRiskResponse result = aiServiceClient.getRiskScore(request);
        return ResponseEntity.ok(ApiResponse.success("AI risk assessment completed", result));
    }

    @GetMapping("/risk-alerts")
    @Operation(
        summary = "List AI security risk alerts",
        description = "Proxies GET /api/risk-alerts from the Python AI service. "
                    + "Returns all risk alerts generated by the AI security monitoring engine (Step 8)."
    )
    public ResponseEntity<ApiResponse<AiRiskAlertResponse>> getRiskAlerts() {
        AiRiskAlertResponse result = aiServiceClient.getRiskAlerts();
        return ResponseEntity.ok(ApiResponse.success("Risk alerts retrieved", result));
    }

    @GetMapping("/health")
    @Operation(summary = "Check AI microservice availability")
    public ResponseEntity<ApiResponse<Map<String, Object>>> aiHealth() {
        boolean healthy = aiServiceClient.isAiServiceHealthy();
        Map<String, Object> status = Map.of(
            "aiServiceReachable", healthy,
            "aiServiceUrl", "http://localhost:8000"
        );
        String message = healthy
                ? "Python AI microservice is reachable and healthy"
                : "Python AI microservice is NOT reachable — start with: uvicorn app.main:app --port 8000";
        return ResponseEntity.ok(ApiResponse.success(message, status));
    }
}
